//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbStudent
    {
        public int id { get; set; }
        public string nins { get; set; }
        public string nama { get; set; }
        public string jk { get; set; }
        public string tempat_lahir { get; set; }
        public Nullable<System.DateTime> tanggal_lahir { get; set; }
        public string kelas { get; set; }
        public string jurusan { get; set; }
        public Nullable<System.DateTime> tanggal_update { get; set; }
    }
}
